/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package techcorpgestion;

/**
 *
 * @author Informatica
 */
public class AplicacionGestionv5 extends javax.swing.JFrame {

    // Modelo de la tabla
    private javax.swing.table.DefaultTableModel modeloTabla; //es un objeto que esta instanciado, es para que podamos estructurar de acuerdo a lo que queremos que muestre en la grilla
    private java.util.ArrayList<Empleado> empleados; //variable del tipo arraylist. el arraylist contiene una estructura del tipo empleado(con sus propiedades y metodos)
    private String operacion = ""; // i=inserción, m=modificación, e=eliminación
    
    /**
     * Creates new form AplicacionGestionv2
     */
    public AplicacionGestionv5() { //metodo constructor, mismo nombre de la clase (por eso no lleva nada al lado del public)
        initComponents(); //VA CONSTRUYENDO TODOS LOS OBJETOS QUE VAAMOS DISEÑANDO EN LA INTERFAZ GRAFICA 
        inicializarDatos(); //se van creando nuevos datos q despues se insertan en empleado
        configurarTabla();
        cargarTabla();
        deshabilitarEdicion();
        configurarEventos();
        // Mostrar datos del primer elemento al iniciar
        if (modeloTabla.getRowCount() > 0) {
            tblListado.setRowSelectionInterval(0, 0);
            mostrarDatosEnPanel(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        pnlListado = new javax.swing.JPanel();
        scpListado = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        pnlEditor = new javax.swing.JPanel();
        pnlDato = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        lblEspecializacion = new javax.swing.JLabel();
        txtEspecializacion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtTextoBuscado = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAumentarSalario = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scpListado.setViewportView(tblListado);

        javax.swing.GroupLayout pnlListadoLayout = new javax.swing.GroupLayout(pnlListado);
        pnlListado.setLayout(pnlListadoLayout);
        pnlListadoLayout.setHorizontalGroup(
            pnlListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpListado, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlListadoLayout.setVerticalGroup(
            pnlListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpListado, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab.addTab("Listado", pnlListado);

        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipo.setText("Tipo");
        lblTipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre");
        lblNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("Id");
        lblId.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSalario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSalario.setText("Salario");
        lblSalario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEspecializacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEspecializacion.setText("Especialización");
        lblEspecializacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlDatoLayout = new javax.swing.GroupLayout(pnlDato);
        pnlDato.setLayout(pnlDatoLayout);
        pnlDatoLayout.setHorizontalGroup(
            pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatoLayout.createSequentialGroup()
                        .addGroup(pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtNombre)))
                    .addGroup(pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDatoLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatoLayout.createSequentialGroup()
                            .addComponent(lblEspecializacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtEspecializacion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        pnlDatoLayout.setVerticalGroup(
            pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDatoLayout.createSequentialGroup()
                        .addGroup(pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspecializacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEspecializacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnInsertar.setText("Insertar");

        btnModificar.setText("Modificar");

        btnEliminar.setText("Eliminar");

        btnBuscar.setText("Buscar");

        btnAumentarSalario.setText("Aumentar salario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTextoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnAumentarSalario)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTextoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAumentarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfirmar.setText("Confirma");

        btnCancelar.setText("Cancela");

        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnPrimero.setText("|<");

        btnAnterior.setText("<<");

        btnSiguiente.setText(">>");

        btnUltimo.setText(">|");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrimero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUltimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPrimero)
                                .addComponent(btnAnterior)
                                .addComponent(btnSiguiente)
                                .addComponent(btnUltimo))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout pnlEditorLayout = new javax.swing.GroupLayout(pnlEditor);
        pnlEditor.setLayout(pnlEditorLayout);
        pnlEditorLayout.setHorizontalGroup(
            pnlEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditorLayout.createSequentialGroup()
                .addGroup(pnlEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlEditorLayout.setVerticalGroup(
            pnlEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditorLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab.addTab("Editor", pnlEditor);

        mnuArchivo.setText("Archivo");

        mnuSalir.setText("Salir");
        mnuArchivo.add(mnuSalir);

        mnuPrincipal.add(mnuArchivo);

        mnuAyuda.setText("Ayuda");

        mnuAcercaDe.setText("Acerca de...");
        mnuAyuda.add(mnuAcercaDe);

        mnuPrincipal.add(mnuAyuda);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );

        tab.getAccessibleContext().setAccessibleName("Listado");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacionGestionv5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacionGestionv5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacionGestionv5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacionGestionv5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacionGestionv5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAumentarSalario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEspecializacion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JPanel pnlDato;
    private javax.swing.JPanel pnlEditor;
    private javax.swing.JPanel pnlListado;
    private javax.swing.JScrollPane scpListado;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tblListado;
    private javax.swing.JTextField txtEspecializacion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTextoBuscado;
    // End of variables declaration//GEN-END:variables

    private void inicializarDatos() { // Inicializar datos de prueba
        //el contenido del vector es una clase empleado(padre) con sus hijos instanciados guardando en la memoria todo lo que va a contener, la idea es usarlo como padre nomas
        empleados = new java.util.ArrayList<>();//reserva en la memoria lo que va a contener, dentro de este se agrega instancias hijas de empleado
        empleados.add(new Desarrollador("Ana López", "DEV001", 4500, "Java", "Desarrollador"));
        empleados.add(new Gerente("Carlos Ruiz", "MGR001", 7000, "Tecnología", "Gerente"));
        empleados.add(new Disenador("Lucía Méndez", "DES001", 4000, "Figma", "Diseñador"));
        empleados.add(new AnalistaDatos("Miguel Torres", "ANL001", 4200, "Python", "Analista de Datos"));
        
        Desarrollador des = new Desarrollador ();
        des.setNombre("Pedro");
        des.setIdEmpleado("DES002");
        des.setSalario(50000);
        des.setCargo("Desarrollador");
        des.setLenguajePrincipal("Phyton");
        empleados.add(des);
                
        cmbTipo.removeAllItems();
        cmbTipo.addItem("Desarrollador");
        cmbTipo.addItem("Gerente");
        cmbTipo.addItem("Diseñador");
        cmbTipo.addItem("Analista de Datos");
    }
    
    private void configurarTabla() { // Configurar modelo de la tabla
        modeloTabla = (javax.swing.table.DefaultTableModel) tblListado.getModel();
        modeloTabla.setColumnIdentifiers(new String[] {"ID", "Nombre", "Salario", "Cargo", "Especialización"});
        tblListado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblListado.setDefaultEditor(Object.class, null); // impide que se editen las celdas
    }

    private void cargarTabla() { // Cargar todos los empleados en la tabla
        modeloTabla.setRowCount(0); // Limpiar
        for (Empleado e : empleados) { //empleados-> array list que contiene una estructura Empleado(los datos o elementos de la estructura, donde cada elemento contiene un objeto del tipo empleado)
            Object[] fila = {e.getIdEmpleado(), e.getNombre(), String.format("%.2f", e.getSalario()), e.getCargo(), obtenerEspecializacion(e)}; //object es una clase madre de todos los objetos. fila es una variable del tipo object q sera un vector
            modeloTabla.addRow(fila);
        }
       /* for (int i =0; i <empleados.size(); i++) {
            Object [] fila = {empleados.get(i).getIdEmpleado(), empleados.get(i).getNombre(), String.format("%.2f", empleados.get(i).getSalario()), empleados.get(i).getCargo(), obtenerEspecializacion(empleados.get(i))};
            modeloTabla.addRow(fila);
        }*/
        
    }

    private String obtenerEspecializacion(Empleado e) { // Obtener especialización según tipo 
        if (e instanceof Desarrollador) return ((Desarrollador) e).getLenguajePrincipal();
        if (e instanceof Gerente) return ((Gerente) e).getDepartamento();
        if (e instanceof Disenador) return ((Disenador) e).getHerramientaFavorita();
        if (e instanceof AnalistaDatos) return ((AnalistaDatos) e).getHerramientaAnalisis();
        return "";
        //en todos los casos va a devolver a un string(ya sea el lenguaje, departamento, herramientafav o herramientaanalisis)
    }

    
    private void deshabilitarEdicion() { // Deshabilitar panel de edición
        tblListado.setEnabled(true);
        txtTextoBuscado.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnAumentarSalario.setEnabled(true);
        btnInsertar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        
        cmbTipo.setEnabled(false);
        txtNombre.setEnabled(false);
        txtId.setEnabled(false);
        txtSalario.setEnabled(false);
        txtEspecializacion.setEnabled(false);
        btnPrimero.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnSiguiente.setEnabled(true);
        btnUltimo.setEnabled(true);
        btnConfirmar.setEnabled(false);
        btnCancelar.setEnabled(false);

        operacion = "";//variable que va a aguardar el estado, si estoy insertando, modificando o eliminando.
        lblMensaje.setText("");
    }

    private void habilitarEdicion() { // Habilitar panel de edición
        tblListado.setEnabled(false);
        txtTextoBuscado.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnAumentarSalario.setEnabled(false);
        btnInsertar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        
        if (operacion.equals("i")) {
            lblMensaje.setText("Confirme la inserción --->");
            cmbTipo.setEnabled(true);
            txtNombre.setEnabled(true);
            txtId.setEnabled(true);
            txtSalario.setEnabled(true);
            txtEspecializacion.setEnabled(true);
        }
        if (operacion.equals("m")) {
            lblMensaje.setText("Confirme la modificación --->");
             cmbTipo.setEnabled(true);
            txtNombre.setEnabled(true);
            txtId.setEnabled(true);
            txtSalario.setEnabled(true);
            txtEspecializacion.setEnabled(true);
        }
        if (operacion.equals("e")) {
            lblMensaje.setText("Confirme la eliminación --->");
            cmbTipo.setEnabled(false);
            txtNombre.setEnabled(false);
            txtId.setEnabled(false);
            txtSalario.setEnabled(false);
            txtEspecializacion.setEnabled(false);
        }
        btnPrimero.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnSiguiente.setEnabled(false);
        btnUltimo.setEnabled(false);
        btnConfirmar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }

    private void limpiarCampos() { // Limpiar campos del formulario
        txtId.setText("");
        txtNombre.setText("");
        txtSalario.setText("");
        txtEspecializacion.setText("");
        cmbTipo.setSelectedIndex(-1); //para que no apunte a ningun elemento de su lista (si pone 0 apunta al primer elemnto de la lista)
    }

    private void llenarCampos(Empleado e) { // Llenar campos con datos del empleado seleccionado
        txtId.setText(e.getIdEmpleado());
        txtNombre.setText(e.getNombre());
        txtSalario.setText(String.valueOf(e.getSalario()));
        txtEspecializacion.setText(obtenerEspecializacion(e));
        if (e instanceof Desarrollador) cmbTipo.setSelectedItem("Desarrollador");
        else if (e instanceof Gerente) cmbTipo.setSelectedItem("Gerente");
        else if (e instanceof Disenador) cmbTipo.setSelectedItem("Diseñador");
        else if (e instanceof AnalistaDatos) cmbTipo.setSelectedItem("Analista de Datos");
    }

    private void mostrarDatosEnPanel(int fila) { // Mostrar datos del empleado seleccionado en el pnlDato
        if (fila == -1) return;
        String id = (String) modeloTabla.getValueAt(fila, 0); //obtener valor de tal fila
        int indice = buscarIndicePorId(id);
        if (indice != -1) {
            llenarCampos(empleados.get(indice));
        }
    }
    
    private void buscarYPosicionar(int desde, String texto) { // Buscar empleado y posicionarse
        if (texto.isEmpty()) return;
        if (desde == modeloTabla.getRowCount() - 1) {
            int resp = javax.swing.JOptionPane.showConfirmDialog(AplicacionGestionv5.this,
                "La búsqueda empezará desde el inicio.",
                "¿Está seguro?", javax.swing.JOptionPane.YES_NO_OPTION);
            if (resp == javax.swing.JOptionPane.YES_OPTION) {
                desde = -1;
            } else {
                return;
            }
        }
        desde++;
        for (int i = desde; i < modeloTabla.getRowCount(); i++) {
            for (int j = 0; j < modeloTabla.getColumnCount(); j++) {
                Object value = modeloTabla.getValueAt(i, j);
                if (value != null && value.toString().toLowerCase().contains(texto.toLowerCase())) {
                    tblListado.setRowSelectionInterval(i, i);
                    tblListado.scrollRectToVisible(tblListado.getCellRect(i, 0, true));
                    return;
                }
            }
        }
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún empleado con ese texto.");
    }

    private boolean validarCampos() { // Validar campos del formulario
        if (cmbTipo.getSelectedIndex() == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un tipo.");
            return false;
        }
        if (txtId.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un ID.");
            return false;
        }
        if (txtNombre.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un nombre.");
            return false;
        }
        if (txtSalario.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un salario.");
            return false;
        }
        if (txtEspecializacion.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una especialización.");
            return false;
        }
        return true;
    }

    private int buscarIndicePorId(String id) { // Buscar índice por ID
        for (int i = 0; i < empleados.size(); i++) {
            if (empleados.get(i).getIdEmpleado().equalsIgnoreCase(id)) {
                return i;
            }
        }
        return -1;
    }

    private void mostrarResumen() { // Mostrar resumen al salir
        int cantidadDesarrollador = 0, cantidadGerente = 0, cantidadDisenador = 0, cantidadAnalista = 0;
        double sumaSalarios = 0;
        for (Empleado e : empleados) {
            sumaSalarios += e.getSalario();
            if (e instanceof Desarrollador) cantidadDesarrollador++;
            else if (e instanceof Gerente) cantidadGerente++;
            else if (e instanceof Disenador) cantidadDisenador++;
            else if (e instanceof AnalistaDatos) cantidadAnalista++;
        }
        double promedio = empleados.isEmpty() ? 0 : sumaSalarios / empleados.size();

        javax.swing.JOptionPane.showMessageDialog(this,
            "Resumen final:\n" +
            "Total empleados: " + empleados.size() + "\n" +
            "Salario promedio: $" + String.format("%.2f", promedio) + "\n" +
            "Desarrolladores: " + cantidadDesarrollador + "\n" +
            "Gerentes: " + cantidadGerente + "\n" +
            "Diseñadores: " + cantidadDisenador + "\n" +
            "Analistas: " + cantidadAnalista,
            "Resumen", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    private void configurarEventos() { // Configurar todos los eventos
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                int resp = javax.swing.JOptionPane.showConfirmDialog(AplicacionGestionv5.this,
                    "¿Desea salir? Se mostrará el resumen.",
                    "Confirmar salida", javax.swing.JOptionPane.YES_NO_OPTION);
                if (resp == javax.swing.JOptionPane.YES_OPTION) {
                    mostrarResumen();
                    System.exit(0);
                }
            }
        });
        mnuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this,
                    "TechCorp Gestión v3\nCurso: POO - 2do Informática\nVersión: 1.0",
                    "Acerca de", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        });
        tblListado.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    if (tblListado.getSelectedRow() != -1) {
                        mostrarDatosEnPanel(tblListado.getSelectedRow());
                    }
                }
            }
        });
        tblListado.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int fila = tblListado.getSelectedRow();
                    if (fila != -1) {
                        tab.setSelectedComponent(pnlEditor);
                    }
                }
            }
        });
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                operacion = "i";
                limpiarCampos();
                habilitarEdicion();
            }
        });

        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (tblListado.getSelectedRow() == -1) {
                    javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this, "Seleccione un empleado para modificar.");
                    return;
                }
                operacion = "m";
                habilitarEdicion();
            }
        });

        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (tblListado.getSelectedRow() == -1) {
                    javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this, "Seleccione un empleado para eliminar.");
                    return;
                }
                operacion = "e";
                habilitarEdicion();
            }
        });

        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (!validarCampos()) return;
                String id = "", nombre="", especial = "", tipo = "";
                double salario = 0.0;
                try {
                    id = txtId.getText().trim();
                    nombre = txtNombre.getText().trim();
                    salario = Double.parseDouble(txtSalario.getText().trim());
                    especial = txtEspecializacion.getText().trim();
                    tipo = (String) cmbTipo.getSelectedItem();
                } catch (NumberFormatException ex) {
                    javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this, "Salario debe ser un número válido.");
                    return;
                }
                Empleado emp = null;
                switch (tipo) {
                    case "Desarrollador":
                        emp = new Desarrollador(nombre, id, salario, especial, tipo);
                        break;
                    case "Gerente":
                        emp = new Gerente(nombre, id, salario, especial, tipo);
                        break;
                    case "Diseñador":
                        emp = new Disenador(nombre, id, salario, especial, tipo);
                        break;
                    case "Analista de Datos":
                        emp = new AnalistaDatos(nombre, id, salario, especial, tipo);
                        break;
                }
                if (emp == null) return;
                if (operacion.equals("i") && buscarIndicePorId(id) != -1) {
                    javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this, "Ya existe un empleado con ese ID.");
                    return;
                }
                int indice = -1;
                if (operacion.equals("i")) { // inserta
                    empleados.add(emp);
                    indice = modeloTabla.getRowCount()-1;
                    javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this, "Empleado agregado correctamente.");
                }
                if (operacion.equals("m")) { // modifica
                    id = (String) modeloTabla.getValueAt(tblListado.getSelectedRow(), 0);
                    indice = buscarIndicePorId(id);
                    if (indice != -1) {
                        empleados.set(indice, emp);
                        javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this, "Empleado modificado correctamente.");
                    }
                }
                if (operacion.equals("e")) { // elimina
                    id = (String) modeloTabla.getValueAt(tblListado.getSelectedRow(), 0);
                    indice = buscarIndicePorId(id);
                    if (indice != -1) {
                        empleados.remove(indice);
                        javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this, "Empleado eliminado.");
                    }
                }
                cargarTabla();
                deshabilitarEdicion();
                if (modeloTabla.getRowCount() == 0) { // Tabla vacía: nada seleccionado
                    limpiarCampos();
                } else if (indice >= modeloTabla.getRowCount()) { // se eliminó el último o se sale del rango: ir al último
                    tblListado.setRowSelectionInterval(modeloTabla.getRowCount() - 1, modeloTabla.getRowCount() - 1);
                } else { // Mantener la misma posición
                        System.out.println(indice);
                    try {
                    tblListado.setRowSelectionInterval(indice, indice);
                    } catch(Exception ex) {
                        System.out.println("x: "+ex);
                    }
                }
            }
        });

        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                deshabilitarEdicion();
                mostrarDatosEnPanel(tblListado.getSelectedRow());
            }
        });

        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (modeloTabla.getRowCount() > 0) tblListado.setRowSelectionInterval(0, 0);
            }
        });
        
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (tblListado.getSelectedRow() > 0) tblListado.setRowSelectionInterval(tblListado.getSelectedRow() - 1, tblListado.getSelectedRow() - 1);
            }
        });
        
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (tblListado.getSelectedRow() < modeloTabla.getRowCount() - 1) tblListado.setRowSelectionInterval(tblListado.getSelectedRow() + 1, tblListado.getSelectedRow() + 1);
            }
        });
        
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (modeloTabla.getRowCount() > 0) tblListado.setRowSelectionInterval(modeloTabla.getRowCount() - 1, modeloTabla.getRowCount() - 1);
            }
        });
        
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                String texto = txtTextoBuscado.getText().trim();
                if (!texto.isEmpty()) {
                    buscarYPosicionar(tblListado.getSelectedRow(), texto);
                }
            }
        });

        btnAumentarSalario.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                int fila = tblListado.getSelectedRow();
                if (fila == -1) {
                    javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this,
                        "Seleccione un empleado de la tabla.");
                    return;
                }

                String id = (String) modeloTabla.getValueAt(fila, 0);
                int indice = buscarIndicePorId(id);
                Empleado emp = empleados.get(indice);

                String porcentajeString = javax.swing.JOptionPane.showInputDialog(AplicacionGestionv5.this,
                    "Ingrese porcentaje de aumento:", "Aumentar salario", javax.swing.JOptionPane.QUESTION_MESSAGE);
                if (porcentajeString != null && !porcentajeString.trim().isEmpty()) {
                    try {
                        double porcentajeDouble = Double.parseDouble(porcentajeString.trim());
                        emp.aumentarSalario(porcentajeDouble);
                        cargarTabla();
                        mostrarDatosEnPanel(fila);
                        javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this, "Salario actualizado.");
                    } catch (NumberFormatException ex) {
                        javax.swing.JOptionPane.showMessageDialog(AplicacionGestionv5.this, "Porcentaje inválido.");
                    }
                }
            }
        });
    }
    
}

